# Generated by Django 2.2.4 on 2019-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='self_introduce',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='self_introduce'),
        ),
    ]
