# Generated by Django 2.2.4 on 2019-09-22 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_self_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
