# Generated by Django 2.2.4 on 2019-09-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_content_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='fav',
            field=models.IntegerField(default=0, verbose_name='favorite'),
        ),
    ]
