# Generated by Django 2.2.4 on 2019-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_content_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latitude_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='latitude_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='latitude_3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='latitude_4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='latitude_5',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude_3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude_4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude_5',
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
